openai_api:
  base_url: "https://api.openai.com/v1"  # Base URL for OpenAI's GPT models
  api_key_env: "OPENAI_API_KEY"          # Environment variable for OpenAI API key

nvidia_api:
  base_url: "https://build.nvidia.com"   # Base URL for NVIDIA's NeMo models
  api_key_env: "NVIDIA_API_KEY"          # Environment variable for NVIDIA API key

models:
  generation_model: "gpt-4o-mini-2024-07-18"  # Default model for generation
  scoring_model: "nvidia/nemotron-4-340b-reward"  # Default model for scoring
  available_models:
    openai:  # OpenAI models
      - "gpt-4o-2024-05-13"
      - "gpt-4o-2024-08-06"
      - "chatgpt-4o-latest"
      - "gpt-4o-mini-2024-07-18"
    nvidia:  # NVIDIA models
      - "nvidia/nemotron-4-340b-reward"

generation_parameters:
  temperature: 0.2
  top_p: 0.7
  max_tokens: 4096  # Adjust according to model's max output tokens

scoring_parameters:
  max_tokens: 4096  # Adjust according to model's max output tokens

validation:
  min_similarity_score: 0.7  # Example value
