# File paths
file_paths:
  pdf_path: "data/raw/Handbook.pdf"
  toc_json_path: "data/toc_output.json"
  output_folder: "segmented_output"
  output_file: "segmented_output_with_metadata.json"
  train_file_path: 'data/output/train_data.jsonl'
  val_file_path: 'data/output/val_data.jsonl'
  segmented_output_path: 'data/segmented_output/segmented_output.json'
  output_dir: 'data/processed'

# API configurations
openai_api:
  base_url: "https://api.openai.com/v1"

nvidia_api:
  base_url: "https://build.nvidia.com"

# Model configurations
models:
  generation_model: "gpt-4o-mini-2024-07-18"
  scoring_model: "nvidia/nemotron-4-340b-reward"
  segmentation_model: "gpt-4o-mini-2024-07-18"
  available_models:
    openai:
      - "gpt-4o-2024-05-13"
      - "gpt-4o-2024-08-06"
      - "chatgpt-4o-latest"
      - "gpt-4o-mini-2024-07-18"
    nvidia:
      - "nvidia/nemotron-4-340b-reward"

# Generation parameters
generation_parameters:
  temperature: 0.2
  top_p: 0.7
  max_tokens: 4096

# Scoring parameters
scoring_parameters:
  max_tokens: 4096

# Validation parameters
validation:
  min_similarity_score: 0.7

# Augmentation settings
augmentation:
  enabled: true
  techniques:
    - synonym_replacement
    - back_translation

# Training settings
training:
  model_name: 'gpt-4o-mini-2024-07-18'
  n_epochs: 4
  price_per_token: 0.0001
  n_questions: 5